name: Continuous Integration 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-unit-tests:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY}}
      DB_URI: ${{ secrets.DB_URI}}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt
      - name: Running database tests
        run: python tests/test_database.py
      - name: Running API tests
        run: python tests/test_api.py
